
apiVersion: "v1"
kind: "Service"

metadata:
  name: "dss"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: "dss"

spec:
  selector:
    app: "dss"
  {{ if $.Values.NodePort -}}
  type: "NodePort"
  ports:
    - port: 80
      nodePort: {{ $.Values.NodePort }}
  {{ else -}}
  type: "ClusterIP"
  ports:
    - port: 80
  {{ end }}


