
DEBUG: false

ImageNameAnonDss: "ghcr.io/shoce/dss"
ImageTagAnonDss: ""

HostPath: "/opt/dss/"
MountPath: "/dss/downloads/"
DownloadsDir: "/dss/downloads/"
DownloadsDirMaxSize: "123123123123"

NodePort: 0
HttpRouteEnable: false


